apiVersion: websitecd.io/v1
kind: Website
metadata:
  name: spa-restapi-mongo
spec:
  gitUrl: https://github.com/websitecd/websitecd-examples.git
  dir: websites/02-spa-restapi-mongo
## Optional values:
#  branch: main
#  sslVerify: false
  secretToken: TOKENASPARESTAPIMONGO
  envs:
    excluded:
      - prod
